{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "697aee2d_8c3cf490",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 800
      },
      "writtenOn": "2025-02-06T08:51:41Z",
      "side": 1,
      "message": "Checked the debug job, it worked",
      "revId": "1fa012662532aba1e852a6b798d88faa833edb6b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "58b76477_f505cd93",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 789
      },
      "writtenOn": "2025-02-06T14:37:26Z",
      "side": 1,
      "message": "I\u0027m confused here on why the CI bot rejected the CR if the job succeeded.\nLet\u0027s retry.",
      "revId": "1fa012662532aba1e852a6b798d88faa833edb6b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0"
    }
  ]
}